version: '3'
volumes:
  prometheus_data: {}
networks:
  default:
services:
  sense_hat_exporter:
    image: markhnsn/sense_hat_exporter
    restart: unless-stopped
    ports:
    - "8000:8000"
    # Needed for driver access
    privileged: true
    networks:
    - default
  prometheus:
    image: markhnsn/prometheus-arm6
    restart: unless-stopped
    ports:
      - 9090:9090
    networks:
      - default
    volumes:
      - ./prometheus.yml/:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
  node_exporter:
    image: markhnsn/node-exporter-linux-armv6
    restart: unless-stopped
    ports:
      - 9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
  arm_exporter:
    image: carlosedp/arm_exporter
    restart: unless-stopped
    ports:
      - 9243
