global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'raspberry_pi'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'node'
    dns_sd_configs:
      - names:
        - 'node_exporter'
        type: 'A'
        port: 9100
  - job_name: 'arm-exporter'
    dns_sd_configs:
      - names:
        - 'arm_exporter'
        type: 'A'
        port: 9243
  - job_name: 'sense_hat_exporter'
    dns_sd_configs:
      - names:
        - 'sense_hat_exporter'
        type: 'A'
        port: 8000
